import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy — RegKnot',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-dvh bg-[#0a0e1a] text-[#f0ece4]/90">
      <header className="border-b border-white/8 px-5 md:px-10 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/landing" className="font-display text-xl font-bold text-[#f0ece4] tracking-wide">
            RegKnot
          </Link>
          <Link href="/landing" className="font-mono text-xs text-[#6b7594] hover:text-[#f0ece4]/80 transition-colors">
            Back
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 md:px-10 py-10">
        <h1 className="font-display text-3xl font-bold text-[#f0ece4] tracking-wide mb-2">
          Privacy Policy
        </h1>
        <p className="font-mono text-xs text-[#6b7594] mb-8">Effective: April 3, 2026 · Updated: October 5, 2026</p>

        <div className="prose-custom space-y-6 font-mono text-sm leading-relaxed text-[#f0ece4]/75">
          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">1. Information We Collect</h2>
            <p>We collect the following information when you use RegKnot:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><strong>Account data:</strong> email address, name, professional role</li>
              <li><strong>Vessel profiles:</strong> vessel names, IMO numbers, flag states, and other details you provide</li>
              <li><strong>Chat history:</strong> questions you ask and responses generated by the AI</li>
              <li><strong>Usage data:</strong> message counts, feature usage, timestamps</li>
              <li><strong>Documents you upload:</strong> files you attach in chat, such as manuals or procedures</li>
              <li><strong>Payment data:</strong> processed securely by Stripe — we do not store card numbers</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">2. How We Use Your Data</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>To provide and improve the RegKnot service</li>
              <li>To personalize regulatory responses based on your vessel profile</li>
              <li>To process payments and manage subscriptions</li>
              <li>To send service-related communications (account, billing, support)</li>
              <li>To monitor and prevent abuse</li>
            </ul>
            <p className="mt-2">
              Documents you upload are used to answer your questions. If a document is relevant to
              your work, we keep it in your account so later answers can use it, and we may review it
              to improve RegKnot. We never show your documents to other users or use them to answer
              anyone else&apos;s questions. You can delete any document at any time in Account settings.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">3. Data Sharing</h2>
            <p>We do not sell your personal data. We share data only with:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><strong>Stripe:</strong> for payment processing</li>
              <li><strong>Anthropic:</strong> your chat messages, and passages of documents you attach, are sent to Anthropic&apos;s API to generate responses</li>
              <li><strong>OpenAI:</strong> text from your questions and documents is sent to OpenAI&apos;s API to index it for search</li>
              <li><strong>Resend:</strong> for transactional email delivery</li>
            </ul>
            <p className="mt-2">
              We may also disclose data if required by law or to protect our rights.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">4. Data Storage &amp; Security</h2>
            <p>
              Your data is stored on secured servers. Chat history and account data are stored in a
              PostgreSQL database. Passwords are hashed using bcrypt. API communication is encrypted
              via TLS. Documents you upload are stored on our servers and no other user can open them; a
              document that isn&apos;t about maritime work is deleted 7 days after you upload it. We
              retain your data for as long as your account is active. When you delete your account,
              its data is deleted with it; records of payments are kept for accounting.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">5. Your Rights</h2>
            <p>You may:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Export your conversations from Account settings, or request a copy of your data</li>
              <li>Delete your account and its data yourself from Account settings, or ask us to</li>
              <li>Delete any document you upload, from Account settings</li>
              <li>Update your profile information at any time</li>
            </ul>
            <p className="mt-2">
              To exercise these rights, email{' '}
              <a href="mailto:support@regknots.com" className="text-[#2dd4bf] hover:underline">
                support@regknots.com
              </a>.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">6. Cookies</h2>
            <p>
              We use httpOnly cookies for authentication (JWT refresh tokens). We do not use
              third-party tracking cookies or analytics cookies at this time.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">7. Children</h2>
            <p>
              RegKnot is not intended for use by anyone under the age of 18. We do not knowingly
              collect data from children.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">8. Changes</h2>
            <p>
              We may update this policy from time to time. Material changes will be communicated
              via email or in-app notice. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-[#2dd4bf] mb-2">9. Contact</h2>
            <p>
              Questions about privacy? Email us at{' '}
              <a href="mailto:support@regknots.com" className="text-[#2dd4bf] hover:underline">
                support@regknots.com
              </a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
